seminar/urls.py
from django.contrib import admin
from django.urls import path
from app_1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminPanel/',views.adminPanel,name="adminPanel"),
    path('adminPanel/register',views.add_korisnik,name='register'),
    path('login_user', views.login_user, name='login'),
    path('all_users',views.all_users,name='all_users'),
    path('adminPanel/add_predmet',views.add_predmet,name='add_predmet'),
    path('adminPanel/all_upisi',views.display_all_upisi,name='all_upisi'),
    path('logout',views.logout_fun,name='logout'),
    path('profileStudent',views.profileStudent,name='profileStudent'),
    path('profileStudent/enroll/<int:predmet_id>/', views.enroll_predmet, name='enroll_predmet'),
    path('profileStudent/withdraw/<int:predmet_id>/', views.withdraw_predmet, name='withdraw_predmet'),
    path('profileProfesor',views.profesorProfile,name='profileProfesor'),
    path('profesorPredmets',views.profesorPredmets,name='profesorPredmets'),
    path('adminPanel/all_students',views.display_all_students,name="all_students"),
    path('adminPanel/all_predmets',views.display_all_predmets,name="all_predmets"),
    path('adminPanel/all_profesors',views.display_all_profesors,name="all_profesors"),
    path('student/<int:studentID>/upisni_list',views.student_upisni_list,name="student_upisni_list"),
    path('adminPanel/add_upisni_list',views.add_upisni_list,name="add_upisni_list"),
    path('adminPanel/editPredmet/<int:predmetID>',views.edit_predmet,name="editPredmet"),
    path('adminPanel/editStudent/<int:studentID>',views.edit_student,name="editStudent"),
    path('adminPanel/editProfesor/<int:profesorID>',views.edit_profesor,name="editProfesor"),
    path('adminPanel/editUpis/<int:upisID>',views.edit_upis,name="editUpis"),
    path('adminPanel/assignNositelj',views.assign_nositelj,name="assignNositelj"),
    path('editStatus/<int:studentID>/<int:subjectID>',views.edit_student_status,name="editStatus"),
    path('studenti10ects',views.studenti_sa_vise_od_10_ects,name="studenti10ects"),
    path('home',views.home,name='home')


]

app_1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Korisnik(AbstractUser):
    roles = (('admin','administrator'),('prof','profesor'),('stud','student'))
    role = models.CharField(max_length=50,choices=roles)
    statuses = (('none','none'),('izv','izvanredni'),('red','redovni'))
    status = models.CharField(max_length=50,choices=statuses)


class Predmeti(models.Model):
    name = models.CharField(max_length=255)
    kod = models.CharField(max_length=16)
    program = models.CharField(max_length=255)
    sem_red = models.IntegerField()
    sem_izv = models.IntegerField()
    ects = models.IntegerField()

    izbor = (('da','da'),('ne','ne'))
    izborni = models.CharField(max_length=10,choices=izbor)

    nositelj = models.ForeignKey(Korisnik,on_delete=models.SET_NULL,null=True,limit_choices_to={'role':'prof'})
    
    def __str__(self):
        return self.name


class Upisi(models.Model):
    student = models.ForeignKey(Korisnik,on_delete=models.CASCADE)
    predmet = models.ForeignKey(Predmeti,on_delete=models.CASCADE)
    statusi = (('failed','failed'),('passed','passed'),('enr','enrolled'),('nenr','notEnrolled'))
    status = models.CharField(max_length=50,choices=statusi)
    class Meta:
        unique_together = ('student','predmet')

app_1/forms.py
from typing import Any, Mapping
from django.core.files.base import File
from django.db.models.base import Model
from django.forms import ModelForm
from django import forms
from django.forms.utils import ErrorList
from .models import Korisnik,Predmeti,Upisi
from django.contrib.auth.hashers import make_password



class FormKorisnik(ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat the Password', widget=forms.PasswordInput)
    class Meta:
        model = Korisnik
        fields = ['first_name','last_name','username','email','role','status']
        help_texts = {
            'username':'(Slova, znamenke i @/./+/_)',
            'status':'(Za profesor ili admin postaviti NONE)'
        }
    # def clean_password(self):
    #     password = make_password(self.cleaned_data.get('password'))
    #     return password
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.password = make_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    
class FormEditKorisnik(ModelForm):
    class Meta:
        model = Korisnik
        fields = ['first_name','last_name','username','email','role','status']
        help_texts = {
            'username':'(Slova, znamenke i @/./+/_)',
            'status':'(Za profesor ili admin postaviti NONE)'
        }

class CustomAuthenticationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())



class FormPredmet(forms.ModelForm):
    class Meta:
        model = Predmeti
        fields = ['name','kod','program','sem_red','sem_izv','ects','izborni','nositelj']
        widgets = {
            'name': forms.TextInput(),
            'kod': forms.TextInput(),
            'program': forms.TextInput(),
            'sem_red': forms.NumberInput(),
            'sem_izv': forms.NumberInput(),
            'ects': forms.NumberInput(),
        }

class FormLogout(forms.Form):
    pass


class FormUpisniList(forms.ModelForm):
    class Meta:
        model = Upisi
        fields = ['student','predmet','status']

    
    def __init__(self,*args,**kwargs):
        super(FormUpisniList,self).__init__(*args,**kwargs)
        self.fields['student'].queryset = Korisnik.objects.filter(role='stud')
    
    
class FormAssignNositelj(forms.Form):
    predmeti = forms.ModelChoiceField(queryset=Predmeti.objects.filter(nositelj__isnull=True),label="Predmet")
    nositelj = forms.ModelChoiceField(queryset=Korisnik.objects.filter(role='prof'), label="Nositelj")



class EditStudentStatusForm(forms.Form):
    status = forms.ChoiceField(choices=Upisi.statusi,label='Novi Status')
    

app_1/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .forms import FormKorisnik,CustomAuthenticationForm,FormPredmet,FormLogout,FormUpisniList,FormEditKorisnik,FormAssignNositelj,EditStudentStatusForm
from .models import Korisnik,Upisi,Predmeti
from django.contrib.auth.decorators import login_required
from .decorators import admin_required
from django.db.models import Q,Sum
# Create your views here.
def home(request):
    nesto="Welcome"
    return render(request,'home.html',{'nesto':nesto})


def add_korisnik(request):
    if request.method == 'GET':
        form = FormKorisnik()
        return render(request,'add_korisnik.html',{'form':form})
    elif request.method == 'POST':
        form = FormKorisnik(request.POST)
        if form.is_valid():
            print(form.cleaned_data.get('password1'))
            print(form.cleaned_data)
            form.save()
            return redirect('all_users')
        
def login_user(request):
    if request.method == 'POST':
        form =  CustomAuthenticationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request,username = username,password = password)
            if user is not None:
                login(request,user)
                if user.role == 'stud':
                    return redirect('profileStudent')
                elif user.role == 'admin':
                    return redirect('adminPanel')
                elif user.role == 'prof':
                    return redirect('profileProfesor')
            else:
                form.add_error(None,'Invalid username or password!')
    else:
        form = CustomAuthenticationForm()
    return render(request,'login.html',{'form':form})

@login_required
def logout_fun(request):
    if request.method == 'POST':
        form = FormLogout(request.POST)
        if form.is_valid():
            logout(request)
            return redirect('login')
    else:
        form = FormLogout()
    return render(request,'logout.html',{'form':form})

@login_required
def profileStudent(request):
    student = Korisnik.objects.get(id=request.user.id)
    predmeti = Predmeti.objects.all()
    # upisi = Upisi.objects.filter(student=student)
    polozeni_predmeti_prva_god = []
    polozeni_predmeti_druga_god = []
    # predmeti = [upis.predmet for upis in upisi]
    upisani_predmeti = Upisi.objects.filter(student=student).values_list('predmet_id', flat=True)
    polozeni_predmeti = Upisi.objects.filter(student=student, status='passed').values_list('predmet_id', flat=True)
    print("Polozeni:"+str(polozeni_predmeti))
    prvi_drugi_semestar = Predmeti.objects.filter(Q(sem_red=1) | Q(sem_red=2))
    treci_cetvrti_semestar = Predmeti.objects.filter(Q(sem_red=3) | Q(sem_red=4))
    prvi_drugi_semestar_ids = prvi_drugi_semestar.values_list('id', flat=True)
    treci_cetvrti_semestar_ids = treci_cetvrti_semestar.values_list('id', flat=True)
    #print("Predmeti 1. i 2. semestar"+str(prvi_drugi_semestar))
    polozeni_predmeti_prva_god = [predmet_id for predmet_id in prvi_drugi_semestar_ids if predmet_id in polozeni_predmeti]
    polozeni_predmeti_druga_god = [predmet_id for predmet_id in treci_cetvrti_semestar_ids if predmet_id in polozeni_predmeti]
    svi_prvi_drugi_polazeni = set(prvi_drugi_semestar_ids) == set(polozeni_predmeti_prva_god)
    svi_treci_cetvrti_polazeni = set(treci_cetvrti_semestar_ids) == set(polozeni_predmeti_druga_god)
    print("Polozeni sa prve godine"+str(polozeni_predmeti_prva_god))
    print("Polozeni sa druge godine"+str(polozeni_predmeti_druga_god))
    svi_predmeti_polozeni = svi_prvi_drugi_polazeni and svi_treci_cetvrti_polazeni
    # Podesi zastavicu upisan za svaki predmet
    for predmet in predmeti:
        if predmet.id in upisani_predmeti:
            predmet.upisan = True
        else:
            predmet.upisan = False
    prikazani_predmeti=[]
    for predmet in predmeti:
        if svi_predmeti_polozeni:
            prikazani_predmeti.append(predmet)
        else:
            if predmet.sem_red > 2 and not svi_prvi_drugi_polazeni:
                continue
        
            # if predmet.sem_red > 4 and not svi_treci_cetvrti_polazeni:
            #     continue
            prikazani_predmeti.append(predmet)
    print("Prikazani:"+str(prikazani_predmeti))
    return render(request, 'profileStudent.html', {'predmeti': prikazani_predmeti})

@login_required
def enroll_predmet(request, predmet_id):
    student = Korisnik.objects.get(id=request.user.id)
    predmet = Predmeti.objects.get(id=predmet_id)
    upisani_predmeti = Upisi.objects.filter(student=student).values_list('predmet_id', flat=True)
    
    if Upisi.objects.filter(student=student, predmet=predmet).exists():
        return redirect('profileStudent')
    
    Upisi.objects.create(student=student, predmet=predmet, status='enrolled')
    return redirect('profileStudent')

@login_required
def withdraw_predmet(request, predmet_id):
    student = Korisnik.objects.get(id=request.user.id)
    predmet = Predmeti.objects.get(id=predmet_id)
    

    upis = Upisi.objects.filter(student=student, predmet=predmet).first()
    if not upis:
        return redirect('profileStudent')

    upis.delete()
    return redirect('profileStudent')

@login_required
def profesorPredmets(request):
    predmet_sa_studentima = []
    profesor = request.user
    predmeti = Predmeti.objects.filter(nositelj=profesor)
    print(predmeti)
    for subject in predmeti:
        upisi = Upisi.objects.filter(predmet=subject).exclude(status='nenr')
        print(upisi)
        studenti_sa_statusima = [{'student':upis.student,'status':upis.status} for upis in upisi]
        predmet_sa_studentima.append({'subject':subject,'studenti':studenti_sa_statusima})
    sort_key = request.GET.get('sort', '')
    for predmet in predmet_sa_studentima:
        studenti = predmet['studenti']
        if sort_key == 'lost':
            studenti.sort(key=lambda x: 0 if x['status'] == 'failed' else (1 if x['status'] == 'enr' else 2))
        elif sort_key == 'pending':
            studenti.sort(key=lambda x: 0 if x['status'] == 'enr' else (1 if x['status'] == 'passed' else 2))
        elif sort_key == 'passed':
            studenti.sort(key=lambda x: 0 if x['status'] == 'passed' else (1 if x['status'] == 'enr' else 2))

    return render(request,'profesorPredmets.html',{'predmet_sa_studentima':predmet_sa_studentima})

def profesorProfile(request):
    return render(request,'profileProfesor.html',{})

@login_required
def all_users(request):
    users = Korisnik.objects.all()
    return render(request,'all_users.html',{'users':users})

@admin_required
def add_predmet(request):
    if request.method == 'POST':
        form = FormPredmet(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = FormPredmet()
    return render(request,'add_predmet.html',{'form':form})

def display_all_upisi(request):
    upisi = Upisi.objects.all()
    return render(request,'all_upisi.html',{'upisi':upisi})


def display_all_students(request):
    students = Korisnik.objects.filter(role='stud')
    #print("Studenti: "+str(students))
    return render(request,'all_students.html',{'students':students})

def student_upisni_list(request,studentID):
    upisni = Upisi.objects.filter(student=Korisnik.objects.get(pk=studentID)).all()
    print(upisni)
    return render(request,'upisni_list.html',{'upisni':upisni})

def add_upisni_list(request):
    if request.method == 'POST':
        form = FormUpisniList(request.POST)
        if form.is_valid():
            form.save()
            return redirect("add_upisni_list")
    else:
        form = FormUpisniList()
    return render(request,'add_upisni_list.html',{'form':form})

@admin_required
def adminPanel(request):
    admin = request.user.username
    return render(request,'adminPanel.html',{'admin':admin})

def display_all_predmets(request):
    predmets = Predmeti.objects.all()
    return render(request,'all_predmets.html',{'predmets':predmets})

def display_all_profesors(request):
    profesors = Korisnik.objects.filter(role='prof')
    print("Profesori: "+str(profesors))
    return render(request,'all_profesors.html',{'profesors':profesors})


def edit_predmet(request,predmetID):
    predmet = Predmeti.objects.get(id=predmetID)
    print(predmet)
    if request.method == 'POST':
        form = FormPredmet(request.POST, instance=predmet)
        if form.is_valid():
            form.save()
            return redirect('all_predmets')
        
    else:
        form = FormPredmet(instance=predmet)
    return render(request,'edit_predmet.html',{'form':form})


def edit_student(request,studentID):
    student = Korisnik.objects.get(pk = studentID)
    print(student)
    if request.method == 'POST':
        form = FormEditKorisnik(request.POST,instance=student)
        if form.is_valid():
            form.save()
            return redirect('all_students')
    else:
        form = FormEditKorisnik(instance=student)
    return render(request,'edit_student.html',{'form':form})


def edit_profesor(request,profesorID):
    profesor = Korisnik.objects.get(pk = profesorID)
    print(profesor)
    if request.method == 'POST':
        form = FormEditKorisnik(request.POST,instance=profesor)
        if form.is_valid():
            form.save()
            return redirect('all_profesors')
    else:
        form = FormEditKorisnik(instance=profesor)
    return render(request,'edit_profesor.html',{'form':form})


def edit_upis(request,upisID):

app_1/templates/add_korisnik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registracija</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f8ff;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: flex-start;
            min-height: 100vh;
        }

        .container {
            border: 3px solid skyblue;
            padding: 20px;
            border-radius: 10px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            position: relative;
            text-align: center;
        }

        input[type="text"], input[type="number"], input[type="email"],input[type="password"], select {
            width: calc(100% - 22px);
            padding: 10px;
            margin: 4px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 1em;
        }

        input[type="submit"] {
            background-color: skyblue;
            border: none;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            display: inline-block;
            font-size: 1em;
            margin-top: 10px;
            cursor: pointer;
            border-radius: 5px;
        }

        input[type="submit"]:hover {
            background-color: deepskyblue;
        }

        .back_button {
            padding: 10px 20px;
            background-color: skyblue;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            display: inline-block;
            margin-top: 10px;
        }

        .back_button:hover {
            background-color: deepskyblue;
        }

        .button_container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 10px;
        }

        h1 {
            font-size: 25px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Popunite sva polja kako bi stvorili račun</h1>
        <div class="register">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="button_container">
                    <input type="submit" value="Dodaj Korisnika">
                    <a class="back_button" href="javascript:history.back()">Povratak</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

app_1/templates/add_upisni_list.html
{% block add_upisni_list %}
<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        font-family: Arial, sans-serif;
        background-color: #f0f8ff;
    }
    .container {
        border: 3px solid skyblue;
        padding: 20px;
        border-radius: 10px;
        background-color: white;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 400px;
        width: 100%;
        text-align: center;
        align-items: center;
    }
    h2 {
        margin-bottom: 20px;
    }
    input[type="submit"] {
        background-color: skyblue;
        border: none;
        color: white;
        padding: 10px 20px;
        text-decoration: none;
        display: inline-block;
        font-size: 1em;
        margin-top: 10px;
        cursor: pointer;
        border-radius: 5px;
    }
    input[type="submit"]:hover {
        background-color: deepskyblue;
    }
    .back_button{
        box-sizing: border-box;
        float: right;
        margin: 10px 60px 10px 10px;
        padding: 10px 20px;
        background-color: skyblue;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }
    .back_button:hover{
        background-color: deepskyblue;
    }
    form p {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin: 10px 0;
    }
    form label {
        margin-bottom: 5px;
        font-weight: bold;
    }
    form input[type="text"],
    form input[type="number"],
    form select {
        width: 50%;
        padding: 8px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
</style>
<div class="container">
<h1>Add Upisni List</h1>
<br>
<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
<input type="submit" value="add Upis">
<a class="back_button" href="javascript:history.back()">Povratak</a>
</form>
</div>
{%endblock%}

app_1/templates/all_predmets.html
{% block all_predmets %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f0f8ff;
        margin: 0;
        padding: 20px;
        text-align: center;
    }
    .container {
        max-width: 1000px;
        margin: 0 auto;
    }
    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        border: 1px solid #ddd;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        background-color: white;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    tr:hover {
        background-color: #f1f1f1;
    }
    .edit {
        background-color: skyblue;
        color: white;
        border: none;
        padding: 5px 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 1em;
        cursor: pointer;
        border-radius: 5px;
    }
    .edit:hover {
        background-color: deepskyblue;
    }
    .back_button, .add_button {
        background-color: skyblue;
        color: white;
        text-decoration: none;
        border-radius: 5px;
        padding: 10px 20px;
        margin: 10px;
        text-align: center;
    }
    .back_button:hover, .add_button:hover {
        background-color: deepskyblue;
    }
</style>
<div class="container">
    <div class="header">
        <a class="back_button" href="javascript:history.back()">Povratak na Admin Panel</a>
        <a class="add_button" href="add_predmet">Dodaj Novi Predmet</a>
    </div>
    <table>
        <tr>
            <th>Predmet</th>
            <th>Kod</th>
            <th>Program</th>
            <th>Semestar(Redovni)</th>
            <th>Semestar(Izvandredni)</th>
            <th>ECTS</th>
            <th>Izborni</th>
            <th>Nositelj</th>
        </tr>
        {% for predmet in predmets %}
        <tr>
            <td>{{ predmet.name }}</td>
            <td>{{ predmet.kod }}</td>
            <td>{{ predmet.program }}</td>
            <td>{{ predmet.sem_red }}</td>
            <td>{{ predmet.sem_izv }}</td>
            <td>{{ predmet.ects }}</td>
            <td>{{ predmet.izborni }}</td>
            <td>{{ predmet.nositelj }}</td>
            <td><a class="edit" href="editPredmet/{{ predmet.id }}">Edit</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app_1/templates/all_profesors.html
{% block all_profesors %}
<style>
body {
        font-family: Arial, sans-serif;
        background-color: #f0f8ff;
        margin: 0;
        padding: 20px;
        text-align: center;
    }
    .container {
        max-width: 1000px;
        margin: 0 auto;
    }
    .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }
    table {
        width: 100%;
        max-width: 800px;
        margin: 0 auto;
        border-collapse: collapse;
        border: 1px solid #ddd;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        background-color: white;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    tr:hover {
        background-color: #f1f1f1;
    }
    input[type="button"] {
        background-color: skyblue;
        color: white;
        border: none;
        padding: 5px 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 1em;
        cursor: pointer;
        border-radius: 5px;
    }
    input[type="button"]:hover {
        background-color: deepskyblue;
    }
    .edit {
        background-color: skyblue;
        color: white;
        border: none;
        padding: 5px 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 1em;
        cursor: pointer;
        border-radius: 5px;
    }
    .edit:hover {
        background-color: deepskyblue;
    }
    .back_button, .add_button{
        box-sizing: border-box;
        float: right;
        margin: 10px 10px 10px 10px;
        padding: 10px 20px;
        background-color: skyblue;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }
    .back_button:hover, .add_button:hover{
        background-color: deepskyblue;
    }
</style>
<div class="container">
    <div class="header">
        <a class="back_button" href="javascript:history.back()">Povratak na Admin Panel</a>
        <a class="add_button" href="register">Dodaj Novog Profesora</a>
    </div>
<table>
    <tr>
        <th>Profesor ID</th>
        <th>Username</th>
        <th>Last name</th>
        <th>First name</th>
        <th>Email</th>
        <th>Predmeti</th>
    </tr>
{% for profesor in profesors %}
<tr>
    <td>{{ profesor.id }}</td>
    <td>{{ profesor.username }}</td>
    <td>{{ profesor.last_name }}</td>
    <td>{{ profesor.first_name }}</td>
    <td>{{ profesor.email }}</td>
    <td><a class="edit" href="editProfesor/{{ profesor.id }}">Pregled/Edit</a></td>
</tr>
{%endfor%}
</table>
</div>
{%endblock%}

app_1/templates/all_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Users</title>
</head>
<body>
    <h2>All Users</h2>
    <table>
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.get_role_display }}</td>
            <td>{{ user.get_status_display }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

app_1/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f0f8ff;
            text-align: center;
            padding-top: 50px;
            justify-content: flex-start;
        }
        h3 {
            margin-bottom: 10px;
        }
        .links {
            display: flex;
            justify-content: center;
            gap: 20px;
            width: 100%;
            max-width: 400px;
        }
        form {
            margin-right: 20px;
        }
        a {
            background-color: skyblue;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 1.1em;
            cursor: pointer;
            border-radius: 5px;
            line-height: 2.5;
            
        }
        a:hover {
            background-color: deepskyblue;
        }
    </style>
</head>
<body>
    <h3>Dobrodošli na Stranicu E-upisi.
        <br>Kako bi pristupili mogućnostima ulogirajte se u sustav.</h3>
    <div class="links">
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Nemate račun? Registrirajte se.</a>
    </div>
</body>
</html>